### ISSUE TITLE
make `cloud_project` config not required for local

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#445]
Once #444 merged, `cloud_project` is actually a required configuration in both local and cloud running settings.
Suggest to make two changes:
1. Add required checking for it in `read_and_validate_input_config`.
2. Rename it to a general name, without term `local` or `cloud`. Since `project` is a bit common and may conflict to other things, I propose as `project_name`.

@lszekeres @jonathanmetzman

**Comment by lszekeres** [comment]
I'd suggest the following: make GCE-specific fields (such as `cloud_project`, `cloud_compute_zone`, `preemptible_runners`, etc) sub-fields of say a `gce` field in the yaml config. e.g.:
```
gce:
  cloud_project: fuzzbench
  cloud_compute_zone: us-central1-a
  preemptible_runners: true
```

and `gce` should be optional (and unused in the local case). wdyt?
