### ISSUE TITLE
Local: Unable to find image if  image URL contains experiment tag

### ISSUE THREAD

**Issue by jiradeto** [google/fuzzbench#619]
Git hash: a634c2f5d1c78af6ee1b0f6165bff951a600078d

When running with local mode, the trial runners did not seem to start.  

Here is the log taken from `/tmp/runner-log.txt` in `dispatcher-container`
```
Unable to find image 'gcr.io/fuzzbench/runners/afl/proj4-2017-08-14:august1' localldodocdocker: Error response from daemon: manifest for gcr.io/fuzzbench/runners/fairfuzz/libxml2-v2.9.2:august1 not found: manifest unknown: Failed to fetch "august1" from request "/v2/fuzzbench/runners/fairfuzz/libxml2-v2.9.2/manifests/august1".
See 'docker run --help'.
elp'.
```

The command I used to run an experiment:
```
PYTHONPATH=. python3 experiment/run_experiment.py \
--experiment-config /expr/local-experiment-config.yaml \
--benchmarks proj4-2017-08-14 libxml2-v2.9.2 \
--experiment-name august1 \
--fuzzers afl fairfuzz
```

experiment-config.yaml
```yaml
experiment: test-experiment
trials: 5
max_total_time: 86400
docker_registry: gcr.io/fuzzbench
experiment_filestore: /expr/out/experiment-data
report_filestore: /expr/out/web-reports
local_experiment: true
benchmarks: "benchmark-1,benchmark-2"
git_hash: "git-hash"
```
